# -*- coding: utf-8 -*-
"""Sistemas_Lineares.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19daXBORkKuWs4XYPLFeGn9_dFre98ZRU

# Resolvendo Problemas de Engenharia de Bioprocessos e Biotecnologia em *Python*
---

##Sistemas Lineares

Considerando o sistema:

\\
$S_1 =
\begin{cases}
a_{11} x_1 + a_{12} x_2 + \cdots + a_{1n} x_n = b_1 \\
a_{21}x_1 + a_{22} x_2 + \cdots + a_{2n} x_n = b_2 \\
\vdots \\
a_{m1}x_1 + a_{m2} x_2 + \cdots + a_{mn} x_n = b_m
\end{cases}$
(Sistema 1)

\\
É possível escrever as matrizes:

\\
$A_{m,n} = 
 \begin{pmatrix}
  a_{11} & a_{12} & \cdots & a_{1n}  \\
  a_{21} & a_{22} & \cdots & a_{2n}  \\
  \vdots  & \vdots  & \ddots & \vdots\\
  a_{m1} & a_{m2} & \cdots & a_{mn} 
 \end{pmatrix}$
 (Matriz 1)

\\
 $X_{n,1} = 
 \begin{pmatrix}
  x_{1} \\
  x_{2} \\
  \vdots\\
  x_{n}
 \end{pmatrix}$
 (Matriz 2)

\\
 $B_{m,1} = 
 \begin{pmatrix}
  b_{1} \\
  b_{2} \\
  \vdots\\
  b_{m}
 \end{pmatrix}$
 (Matriz 3)


\\
E a equação:

\\
$ A \cdot X = B $

$\begin{pmatrix}
  a_{11} & a_{12} & \cdots & a_{1n}  \\
  a_{21} & a_{22} & \cdots & a_{2n}  \\
  \vdots  & \vdots  & \ddots & \vdots\\
  a_{m1} & a_{m2} & \cdots & a_{mn} 
 \end{pmatrix}$                        <!--- Matriz 1 / Matriz A -->
 $\cdot$
 $\begin{pmatrix}
  x_{1} \\
  x_{2} \\
  \vdots\\
  x_{n}
 \end{pmatrix}$                        <!--- Matriz 2 / Matriz X -->
 $=$
 $\begin{pmatrix}
  b_{1} \\
  b_{2} \\
  \vdots\\
  b_{m}
 \end{pmatrix}$                         <!--- Matriz 3 / Matriz B -->
 (Equação 1)
"""

##### Exemplo do uso da biblioteca NumPy para resolução de sistemas de equações lineares #####

import numpy as np

A = np.array([[1,2],[3,5]])
B = np.array([1,2])
X = np.linalg.solve(A,B)

print("X = ", X)

"""---
# Exemplo de Sistemas Lineares
\\
Considerando um sistema com três destiladores conectados, sem reciclo, operando, como na Figura 1 abaixo, para separar uma mistura de xileno, estireno, tolueno e benzeno.

\\
<center>
Figura 1: Sistema de destiladores

![Sistema_de_destiladores](https://drive.google.com/file/d/1Nt6eC-xvuNH7mG8JbppnnS8xE04g5EG7/view?usp=share_link)

Fonte: KWONG, 2016.
</center>

\\
As concentrações de cada componente da mistura foram medidas na corrente de entrada e nas correntes de saída. Essas concentrações podem ser observadas na Tabela 1, abaixo.

\\
<center>
Tabela 1: Quantidade (%) de cada componente da mistura em cada corrente de entrada ou saída 

 Corrente  | Xileno | Estireno | Tolueno | Benzeno 
 ----------|:------:|:--------:|:-------:|:-------:
 $F$       | 15     | 25       | 40      | 20      
 $D_2$     | 7      | 4        | 54      | 35      
 $B_2$     | 18     | 24       | 42      | 16      
 $D_3$     | 15     | 10       | 54      | 21      
 $B_3$     | 24     | 65       | 10      | 1       

Fonte: KWONG, 2016.
</center>

\\
Para realizar o balanço de massa do sistema, é necessário considerar:
- Os componentes de índices:
  - $1$, Xileno
  - $2$, Estireno
  - $3$, Tolueno
  - $4$, Benzeno
- Os fluxos:
  - $F$ de entrada
  - $D_1$ de saída superior do destilador 1 e entrada do destilador 2
  - $B_1$ de saída inferior do destilador 1 e entrada do destilador 2
  - $D_2$ de saída superior do destilador 2
  - $B_2$ de saída inferior do destilador 2
  - $D_3$ de saída superior do destilador 3
  - $B_3$ de saída inferior do destilador 3
- As concentrações (%) de cada fluxo:
  - $z$ do fluxo F
  - $y_{ij}$ do fluxo $D_i$, componente $j$
  - $x_{ij}$ do fluxo $B_i$, componente $j$

\\
Com base nas considerações, é possível equacionar:
- A relação entre os fluxos:

$\begin{cases}
F = D_1 + B_1 \\
D_1 = D_2 + B_2 \\
B_1 = D_3 + B_3
\end{cases}$

- O balanço de massa global:

$\begin{cases}
D_2 y_{21} + B_2 x_{21} + D_3 y_{31} + B_3 x_{31} = F z_1 \\
D_2 y_{22} + B_2 x_{22} + D_3 y_{32} + B_3 x_{32} = F z_2 \\
D_2 y_{23} + B_2 x_{23} + D_3 y_{33} + B_3 x_{33} = F z_3 \\
D_2 y_{24} + B_2 x_{24} + D_3 y_{34} + B_3 x_{34} = F z_1
\end{cases}$

- A equação matricial do balanço de massa global:

$\begin{pmatrix}
y_{21} & x_{21} & y_{31} & x_{31} \\
y_{22} & x_{22} & y_{32} & x_{32} \\
y_{23} & x_{23} & y_{33} & x_{33} \\
y_{24} & x_{24} & y_{34} & x_{34}
\end{pmatrix}$
$\cdot$
$\begin{pmatrix}
D_2 \\
B_2 \\
D_3 \\
B_3
\end{pmatrix}$
$=$
$\begin{pmatrix}
F z_1 \\
F z_2 \\
F z_3 \\
F z_4
\end{pmatrix}$
(Equação 2)

- O baçanço de massa para a Coluna 1:

$\begin{cases}
D_1 y_{11} + B_1 x_{11} = F z_1 \\
D_1 y_{12} + B_1 x_{12} = F z_2 \\
D_1 y_{13} + B_1 x_{13} = F z_3 \\
D_1 y_{14} + B_1 x_{14} = F z_4
\end{cases}$

- O balanço de massa para a Coluna 2:

$\begin{cases}
D_2 y_{21} + B_2 x_{21} = D_1 y_{11} \\
D_2 y_{22} + B_2 x_{22} = D_1 y_{12} \\
D_2 y_{23} + B_2 x_{23} = D_1 y_{13} \\
D_2 y_{24} + B_2 x_{24} = D_1 y_{14}
\end{cases}$

- O balanço de massa para a Coluna 3:

$\begin{cases}
D_3 y_{31} + B_3 x_{31} = B_1 y_{11} \\
D_3 y_{32} + B_3 x_{32} = B_1 y_{12} \\
D_3 y_{33} + B_3 x_{33} = B_1 y_{13} \\
D_3 y_{34} + B_3 x_{34} = B_1 y_{14}
\end{cases}$

\\
Com base em todos os sistemas acima, é possível determinar as concentrações de saída ($x$ e $y$); as massas de entrada ($Fz$); e os fluxos de saída do sistema ($D$ e $B$).
"""

from binascii import b2a_base64
########## EXEMPLO DO LIVRO ##########
import numpy as np

#--------------------------------------------------------#
#|              Fluxo de entrada (mol/min)              |#
#--------------------------------------------------------#
F = 70

#--------------------------------------------------------#
#|       Concentracoes da corrente de entrada (%)       |#
#--------------------------------------------------------#
z1 = 15
z2 = 25
z3 = 40
z4 = 20

#--------------------------------------------------------#
#| Concentracoes das correntes de saida da Coluna 2 (%) |#
#--------------------------------------------------------#
# Superior #
y21 = 7
y22 = 4
y23 = 54
y24 = 35
# Inferior #
x21 = 18
x22 = 24
x23 = 42
x24 = 16

#--------------------------------------------------------#
#| Concentracoes das correntes de saida da Coluna 3 (%) |#
#--------------------------------------------------------#
# Superior #
y31 = 15
y32 = 10
y33 = 54
y34 = 21
# Inferior #
x31 = 24
x32 = 65
x33 = 10
x34 = 1

#--------------------------------------------------------#
#|                      Incognitas                      |#
#--------------------------------------------------------#
# x11, x12, x13, x14
# y11, y12, y13, y14
# B1, B2, B3
# D1, D2, D3

#--------------------------------------------------------#
#|                Balaco de massa global                |#
#--------------------------------------------------------#
# Concentracoes das correntes de saida das Colunas 2 e 3 #
A = np.array([[ y21, x21, y31, x31],
              [ y22, x22, y32, x32],
              [ y23, x23, y33, x33],
              [ y24, x24, y34, x34]])
# Massas das correntes de entrada da Coluna 1 #
B = np.array([[F*z1],
              [F*z2],
              [F*z3],
              [F*z4]])
# Resolucao do sistema #
X = np.linalg.solve(A, B)
D2 = X[0]
B2 = X[1]
D3 = X[2]
B3 = X[3]

#--------------------------------------------------------#
#|             Balanco de massa da Coluna 2             |#
#--------------------------------------------------------#
D1 = D2 + B2

D1y11 = D2 * y21 + B2 * x21
D1y12 = D2 * y22 + B2 * x22
D1y13 = D2 * y23 + B2 * x23
D1y14 = D2 * y24 + B2 * x24

y11 = D1y11 / D1
y12 = D1y12 / D1
y13 = D1y13 / D1
y14 = D1y14 / D1

#--------------------------------------------------------#
#|             Balanco de massa da Coluna 3             |#
#--------------------------------------------------------#
B1 = D3 + B3

B1x11 = D3 * y31 + B3 * x31
B1x12 = D3 * y32 + B3 * x32
B1x13 = D3 * y33 + B3 * x33
B1x14 = D3 * y34 + B3 * x34

x11 = B1x11 / B1
x12 = B1x12 / B1
x13 = B1x13 / B1
x14 = B1x14 / B1

#--------------------------------------------------------#
#|                 Impressao da solucao                 |#
#--------------------------------------------------------#

def ImprimeFluxoEConcentracao (entradasaida, fluxo, conc1, conc2, conc3, conc4):
  print(f"{entradasaida}:")
  print("  Fluxo (mol/min) = ", "%.2f"%fluxo)
  print("      Concentrações (%):")
  print("      - Xileno   = ", "%.2f"%conc1)
  print("      - Estireno = ", "%.2f"%conc2)
  print("      - Tolueno  = ", "%.2f"%conc3)
  print("      - Benzeno  = ", "%.2f"%conc4)
  print("\n")

print("----------------------------------------------------")
print("--------------------  COLUNA 1  --------------------")
print("----------------------------------------------------")

ImprimeFluxoEConcentracao ("Entrada", F, z1, z2, z3, z4)


print("----------------------------------------------------")
print("--------------------  COLUNA 2  --------------------")
print("----------------------------------------------------")

ImprimeFluxoEConcentracao ("Entrada", D1, y11, y12, y13, y14)
ImprimeFluxoEConcentracao ("Saída superior", D2, y21, y22, y23, y24)
ImprimeFluxoEConcentracao ("Saída inferior", B2, x21, x22, x23, x24)


print("----------------------------------------------------")
print("--------------------  COLUNA 3  --------------------")
print("----------------------------------------------------")

ImprimeFluxoEConcentracao ("Entrada", B1, x11, x12, x13, x14)
ImprimeFluxoEConcentracao ("Saída superior", D3, y31, y32, y33, y34)
ImprimeFluxoEConcentracao ("Saída inferior", B3, x31, x32, x33, x34)

